name: Build and Release Executable

on:
  push:
    branches:
      - main
      - dev
      - proxy

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r mic_python/python/requirements.txt

    - name: Build executable
      working-directory: mic_python/python
      run: ./build.bat

    - name: Get short SHA
      id: sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v1
      with:
        files: mic_python/python/dist/talker_mic.exe
        tag_name: ${{ steps.sha.outputs.sha }}
        name: Build ${{ steps.sha.outputs.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
